[2024-06-08T09:35:37.931+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:35:32.133120+00:00 [queued]>
[2024-06-08T09:35:37.978+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:35:32.133120+00:00 [queued]>
[2024-06-08T09:35:37.980+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-06-08T09:35:38.056+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): load_to_database> on 2024-06-08 09:35:32.133120+00:00
[2024-06-08T09:35:38.083+0000] {standard_task_runner.py:57} INFO - Started process 697 to run task
[2024-06-08T09:35:38.103+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data_17', 'load_to_database', 'manual__2024-06-08T09:35:32.133120+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpxl4s_ikc']
[2024-06-08T09:35:38.118+0000] {standard_task_runner.py:85} INFO - Job 191: Subtask load_to_database
[2024-06-08T09:35:38.449+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:35:32.133120+00:00 [running]> on host bec75c81cc74
[2024-06-08T09:35:39.540+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dummy@gmail.com' AIRFLOW_CTX_DAG_OWNER='naveed' AIRFLOW_CTX_DAG_ID='ETL_toll_data_17' AIRFLOW_CTX_TASK_ID='load_to_database' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T09:35:32.133120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T09:35:32.133120+00:00'
[2024-06-08T09:35:39.554+0000] {logging_mixin.py:149} INFO - database connected successfully
[2024-06-08T09:35:40.636+0000] {logging_mixin.py:149} INFO - Error while connect to database *** list index out of range
[2024-06-08T09:35:40.641+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-06-08T09:35:40.707+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data_17, task_id=load_to_database, execution_date=20240608T093532, start_date=20240608T093537, end_date=20240608T093540
[2024-06-08T09:35:40.806+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-06-08T09:35:40.846+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
