[2024-06-08T09:24:45.421+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [queued]>
[2024-06-08T09:24:45.439+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [queued]>
[2024-06-08T09:24:45.440+0000] {taskinstance.py:1331} INFO - Starting attempt 3 of 4
[2024-06-08T09:24:45.463+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): load_to_database> on 2024-06-08 09:17:10.411004+00:00
[2024-06-08T09:24:45.470+0000] {standard_task_runner.py:57} INFO - Started process 439 to run task
[2024-06-08T09:24:45.479+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data_17', 'load_to_database', 'manual__2024-06-08T09:17:10.411004+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpu01zu3lk']
[2024-06-08T09:24:45.484+0000] {standard_task_runner.py:85} INFO - Job 163: Subtask load_to_database
[2024-06-08T09:24:45.574+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [running]> on host bec75c81cc74
[2024-06-08T09:24:45.914+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dummy@gmail.com' AIRFLOW_CTX_DAG_OWNER='naveed' AIRFLOW_CTX_DAG_ID='ETL_toll_data_17' AIRFLOW_CTX_TASK_ID='load_to_database' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T09:17:10.411004+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T09:17:10.411004+00:00'
[2024-06-08T09:24:45.922+0000] {logging_mixin.py:149} INFO - database connected successfully
[2024-06-08T09:24:45.925+0000] {logging_mixin.py:149} INFO - Error while connect to database *** not all arguments converted during string formatting
[2024-06-08T09:24:45.926+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-06-08T09:24:45.942+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data_17, task_id=load_to_database, execution_date=20240608T091710, start_date=20240608T092445, end_date=20240608T092445
[2024-06-08T09:24:45.987+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-06-08T09:24:46.022+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
