[2024-06-08T09:26:39.526+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [queued]>
[2024-06-08T09:26:39.546+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [queued]>
[2024-06-08T09:26:39.547+0000] {taskinstance.py:1331} INFO - Starting attempt 4 of 5
[2024-06-08T09:26:39.575+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): load_to_database> on 2024-06-08 09:17:10.411004+00:00
[2024-06-08T09:26:39.583+0000] {standard_task_runner.py:57} INFO - Started process 490 to run task
[2024-06-08T09:26:39.588+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data_17', 'load_to_database', 'manual__2024-06-08T09:17:10.411004+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmplhpzxdoo']
[2024-06-08T09:26:39.591+0000] {standard_task_runner.py:85} INFO - Job 171: Subtask load_to_database
[2024-06-08T09:26:39.666+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [running]> on host bec75c81cc74
[2024-06-08T09:26:40.029+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dummy@gmail.com' AIRFLOW_CTX_DAG_OWNER='naveed' AIRFLOW_CTX_DAG_ID='ETL_toll_data_17' AIRFLOW_CTX_TASK_ID='load_to_database' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T09:17:10.411004+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T09:17:10.411004+00:00'
[2024-06-08T09:26:40.035+0000] {logging_mixin.py:149} INFO - database connected successfully
[2024-06-08T09:26:40.039+0000] {logging_mixin.py:149} INFO - Error while connect to database *** not all arguments converted during string formatting
[2024-06-08T09:26:40.039+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-06-08T09:26:40.056+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data_17, task_id=load_to_database, execution_date=20240608T091710, start_date=20240608T092639, end_date=20240608T092640
[2024-06-08T09:26:40.093+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-06-08T09:26:40.118+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
